name: Deploy to iims.uthscsa.edu (prod)

on:
  push:
    branches:
      - env/prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3
      with:
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.DEPLOYMENT_SSH_KEY_PRIVATE }}
        WPE_ENV: iimsprod
        SRC_PATH: "wp-content/themes/wp-shield/"
        REMOTE_PATH: "wp-content/themes/wp-shield/"
        FLAGS: '-azvr --inplace --exclude=".*" --copy-dirlinks'
