name: Deploy to iims stage (stage)

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Install project dependencies
        run: composer install --no-dev --optimize-autoloader
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm
        run: |
          npm install
          npm run build
          rm -r node_modules
        working-directory: wp-content/themes/wp-shield
      - name: GitHub Action Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
            WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
            WPE_ENV: iimsstg
