name: Deploy to IIMS stage

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: GitHub Action Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_ENV: iimsstg
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPENGINE_SSH_KEY_PRIVATE }}
          REMOTE_PATH: "wp-content/themes/wp-shield/"
          FLAGS: '-azvr --inplace --exclude=".*" --copy-dirlinks'