name: Deploy to WP Engine (Production)

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      #      - name: Install project dependencies
      #        run: composer install --no-dev --optimize-autoloader
      - name: Switch to theme directory
        run: |
            ls
            cd wp-content/themes/wp-shield
            ls
      - name: npm install
        run: npm install
      - name: npm run build
        run: npm run build
      - name: Switch back to root directory
        run: cd ../../../
      - name: SSH Deploy to WP Engine
        uses: bowiedev/github-action-wpengine-ssh-deploy@master
        env:
          WPE_ENV_NAME: utphysicians
          WPE_SSHG_KEY_PUBLIC: ${{ secrets.WPENGINE_SSH_KEY_PUBLIC }}
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPENGINE_SSH_KEY_PRIVATE }}
          TPO_SRC_PATH: ""
          TPO_PATH: ""
