name: Deploy to WP Engine (Production)

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Switch to theme directory
        run: |
          cd wp-content/themes/wp-shield
#      - name: Install composer dependencies
#        uses: php-actions/composer@v6
#        with:
#          dev: no
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: npm install + build
        run: npm install && npm run build
      - name: Switch back to root directory
        run: |
          cd ../../../
      - name: GitHub Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@main
        env:
          WPE_ENV_NAME: utphysicians
          WPE_SSHG_KEY_PUBLIC: ${{ secrets.WPE_SSH_KEY_PUBLIC }}
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSH_KEY_PRIVATE }}
          TPO_SRC_PATH: ""
          TPO_PATH: ""
