name: Deploy to WP Engine (Dev)

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install project dependencies
        run: composer install --no-dev --optimize-autoloader
      - name: npm
        run: |
          npm install
          npm run build
          rm -r node_modules
        working-directory: wp-content/themes/wp-shield
      - name: SSH Deploy to DEV Environments
        uses: bowiedev/github-action-wpengine-ssh-deploy@master
        env:
          WPE_ENV_NAME: devuthealth
          WPE_SSHG_KEY_PUBLIC: ${{ secrets.DEPLOYMENT_SSH_KEY_PUBLIC }}
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.DEPLOYMENT_SSH_KEY_PRIVATE }}
          TPO_SRC_PATH: ""
          TPO_PATH: ""
